- name: Validate DB external flag
  ansible.builtin.assert:
    that:
      - harbor_db_external is boolean

- name: Validate Redis external flag
  ansible.builtin.assert:
    that:
      - harbor_redis_external is boolean

- name: Validate S3 configuration (MinIO)
  ansible.builtin.assert:
    that:
      - s3_endpoint is defined
      - s3_endpoint | length > 0
      - s3_bucket is defined
      - s3_bucket | length > 0
  when: harbor_storage_type == "s3"

- name: Render harbor.yml
  ansible.builtin.template:
    src: harbor.yml.j2
    dest: "{{ harbor_install_dir }}/harbor/harbor.yml"
    mode: "0644"
  register: harbor_config_file

- name: Create Harbor sub-directories with recursive ownership
  ansible.builtin.file:
    path: "{{ harbor_data_dir }}/{{ item }}"
    state: directory
    owner: "10000"
    group: "10000"
    mode: "0700"
    recurse: yes  # This ensures the internal pg15 folder can be created
  with_items:
    - database
    - redis
    - job_logs
  become: true

- name: Ensure Harbor log directory exists
  ansible.builtin.file:
    path: "{{ harbor_log_dir }}"
    state: directory
    owner: "10000"
    group: "10000"
    mode: "0755"
  become: true

- name: Ensure Harbor data directory
  ansible.builtin.file:
    path: "{{ harbor_data_dir }}"
    state: directory
    owner: "10000"
    group: "10000"
    mode: "0755"

- name: Show rendered harbor_hostname
  debug:
    msg: "hostname={{ harbor_hostname }}, external_url={{ harbor_external_url }}"

- name: Validate Harbor hostname or external_url
  ansible.builtin.fail:
    msg: "Either harbor_hostname or harbor_external_url must be set"
  when:
    - harbor_hostname | default('') | length == 0
    - harbor_external_url | default('') | length == 0