---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  become: true

- name: Ensure Docker keyring directory exists
  ansible.builtin.file:
    path: "{{ docker_key_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Download and install Docker GPG key
  ansible.builtin.raw: curl -fsSL {{ docker_gpg_url }} | gpg --dearmor | tee {{ docker_key_path }} > /dev/null && chmod a+r {{ docker_key_path }}
  become: true
  changed_when: false

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_key_path }}] {{ docker_repo_url }} {{ docker_repo_release }} stable"
    filename: docker
    state: present
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Docker engine and components
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Install docker-compose (binary)
  ansible.builtin.get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Verify docker-compose version
  ansible.builtin.command: docker-compose --version
  register: docker_compose_version
  changed_when: false
