# -------------------------
# ACTIVE node failover
# -------------------------
- name: Install ACTIVE failover script
  ansible.builtin.template:
    src: harbor_active_failover.sh.j2
    dest: /usr/local/bin/harbor_failover.sh
    mode: "0755"
  when:
    - harbor_role_mode == "active"
    - not harbor_skip_failover | default(false)

- name: Install ACTIVE failover service
  ansible.builtin.template:
    src: harbor-failover.service.j2
    dest: /etc/systemd/system/harbor-active-failover.service
    mode: "0644"
  vars:
    harbor_failover_role: active
    harbor_failover_script: /usr/local/bin/harbor_failover.sh
  when:
    - harbor_role_mode == "active"
    - not harbor_skip_failover | default(false)

- name: Enable ACTIVE failover service
  ansible.builtin.systemd:
    name: harbor-active-failover
    enabled: true
    state: started
    daemon_reload: true
  when:
    - harbor_role_mode == "active"
    - not harbor_skip_failover | default(false)


# -------------------------
# PASSIVE node failover
# -------------------------
- name: Install PASSIVE failover script
  ansible.builtin.template:
    src: harbor_passive_failover.sh.j2
    dest: /usr/local/bin/harbor_failover.sh
    mode: "0755"
  when:
    - harbor_role_mode == "passive"
    - not harbor_skip_failover | default(false)

- name: Install PASSIVE failover service
  ansible.builtin.template:
    src: harbor-failover.service.j2
    dest: /etc/systemd/system/harbor-passive-failover.service
    mode: "0644"
  vars:
    harbor_failover_role: passive
    harbor_failover_script: /usr/local/bin/harbor_failover.sh
  when:
    - harbor_role_mode == "passive"
    - not harbor_skip_failover | default(false)

- name: Enable PASSIVE failover service
  ansible.builtin.systemd:
    name: harbor-passive-failover
    enabled: true
    state: started
    daemon_reload: true
  when:
    - harbor_role_mode == "passive"
    - not harbor_skip_failover | default(false)