# roles/harbor/tasks/main.yml
---
- name: Set Harbor role mode from tags
  set_fact:
    harbor_role_mode: >-
      {{ 'active' if 'active' in ansible_run_tags else 'passive' }}


- import_tasks: prereqs.yml
- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: service.yml
- import_tasks: systemd.yml
- import_tasks: failover.yml
