---
- name: Install required apt packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Create cert directory
  ansible.builtin.file:
    path: "{{ harbor_cert_dir }}"
    state: directory
    mode: '0755'
