- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart harbor
  systemd:
    name: harbor
    state: restarted

- name: start harbor
  systemd:
    name: harbor
    state: started
    enabled: true

